name: Run Cypress Tests and Publish Report

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd cypress_project
          npm ci

      - name: Run Cypress tests
        run: |
          cd cypress_project
          npm full-regression-headless-chrome
        continue-on-error: true

      - name: Generate HTML Report
        run: |
          cd cypress_project
          node -e "
          const fs = require('fs');
          const report = require('multiple-cucumber-html-reporter');
          const jsonDir = '../cypress_project/cypress/reports/cucumber-json/';
      
          if (!fs.existsSync(jsonDir) || fs.readdirSync(jsonDir).length === 0) {
            throw new Error(\`JSON files not found in '\${jsonDir}'. Ensure tests are run and results are generated.\`);
          }
      
          report.generate({
            jsonDir: jsonDir,
            reportPath: '../cypress_project/cypress/reports/cucumber-html/',
          });
          console.log('HTML Report generated successfully!');
          "

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-report
          path: cypress_project/cypress/reports/cucumber-html/
      
      - name: Commit and Push Report
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          cd cypress_project
          git add ./cypress/reports/cucumber-html/
          git commit -m "Update HTML Report [skip ci]" || echo "No changes to commit"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} main
