name: Run Cypress Tests and Publish Report

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd cypress_project
          npm install

      - name: Run Cypress tests
        run: |
          cd cypress_project
          npm run full-regression-headless-chrome
          
      - name: Generate HTML Report
        run: |
          cd cypress_project
          node github-report.js

      - name: Debug generated report html
        run: ls -R cypress_project/cypress/reports/html-report-github

      - name: Upload HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-html-report
          path: cypress_project/cypress/reports/html-report-github

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: cypress_project/cypress/reports/html-report-github
