name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd cypress_project
          npm install

      - name: Run Cypress tests
        run: |
          npm run full-regression-headless-chrome
          
      - name: Generate HTML Report
        run: |
          node github-report.js

      - name: Upload HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-html-report
          path: /reports_github/
