name: Run Cypress Tests and Publish Report

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd cypress_project
          npm ci

      - name: Run Cypress tests
        run: |
          cd cypress_project
          npm full-regression-headless-chrome
        continue-on-error: true

      - name: Generate HTML Report
        run: |
          cd cypress_project
          node -e "
          const fs = require('fs');
          const report = require('multiple-cucumber-html-reporter');
          const jsonDir = '../cypress_project/cypress/reports/cucumber-json/';
      
          if (!fs.existsSync(jsonDir) || fs.readdirSync(jsonDir).length === 0) {
            throw new Error(\`JSON files not found in '\${jsonDir}'. Ensure tests are run and results are generated.\`);
          }
      
          report.generate({
            jsonDir: jsonDir,
            reportPath: '../cypress_project/cypress/reports/cucumber-html/',
          });
          console.log('HTML Report generated successfully!');
          "
          ls -la ../cypress_project/cypress/reports/cucumber-json/

      - name: Upload HTML Report
        uses: actions/upload-artifact@v6
        with:
          name: cucumber-html-report
          path: cypress_project/cypress/reports/1/

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: cypress_project/cypress/reports/1/
