name: Run Cypress Tests and Publish Report

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd cypress_project
          npm ci

      - name: Run Cypress tests
        run: |
          cd cypress_project
        continue-on-error: true

      - name: List files in reports directory
        run: |
          cd cypress_project
          ls -la /cypress/reports/cucumber-json/
